// Mocks generated by Mockito 5.4.6 from annotations
// in daily_life_tracker/test/providers/achievements_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i4;

import 'package:daily_life_tracker/models/badge_model.dart' as _i5;
import 'package:daily_life_tracker/models/leaderboard_user_model.dart' as _i6;
import 'package:daily_life_tracker/models/user_level_model.dart' as _i2;
import 'package:daily_life_tracker/services/achievements_service.dart' as _i7;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserLevelModel_0 extends _i1.SmartFake
    implements _i2.UserLevelModel {
  _FakeUserLevelModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconData_1 extends _i1.SmartFake implements _i3.IconData {
  _FakeIconData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeColor_2 extends _i1.SmartFake implements _i4.Color {
  _FakeColor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeModel_3 extends _i1.SmartFake implements _i5.BadgeModel {
  _FakeBadgeModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLeaderboardUserModel_4 extends _i1.SmartFake
    implements _i6.LeaderboardUserModel {
  _FakeLeaderboardUserModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AchievementsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementsService extends _i1.Mock
    implements _i7.AchievementsService {
  MockAchievementsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i5.BadgeModel>> fetchUserBadges() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserBadges, []),
            returnValue: _i8.Future<List<_i5.BadgeModel>>.value(
              <_i5.BadgeModel>[],
            ),
          )
          as _i8.Future<List<_i5.BadgeModel>>);

  @override
  _i8.Future<_i2.UserLevelModel> fetchUserLevel() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserLevel, []),
            returnValue: _i8.Future<_i2.UserLevelModel>.value(
              _FakeUserLevelModel_0(
                this,
                Invocation.method(#fetchUserLevel, []),
              ),
            ),
          )
          as _i8.Future<_i2.UserLevelModel>);

  @override
  _i8.Future<void> updateBadgeProgress(String? badgeId, double? progress) =>
      (super.noSuchMethod(
            Invocation.method(#updateBadgeProgress, [badgeId, progress]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> earnBadge(String? badgeId) =>
      (super.noSuchMethod(
            Invocation.method(#earnBadge, [badgeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addXP(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#addXP, [amount]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.LeaderboardUserModel>> fetchLeaderboard() =>
      (super.noSuchMethod(
            Invocation.method(#fetchLeaderboard, []),
            returnValue: _i8.Future<List<_i6.LeaderboardUserModel>>.value(
              <_i6.LeaderboardUserModel>[],
            ),
          )
          as _i8.Future<List<_i6.LeaderboardUserModel>>);

  @override
  _i8.Future<void> checkBadgeProgress() =>
      (super.noSuchMethod(
            Invocation.method(#checkBadgeProgress, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [UserLevelModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLevelModel extends _i1.Mock implements _i2.UserLevelModel {
  MockUserLevelModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentLevel =>
      (super.noSuchMethod(Invocation.getter(#currentLevel), returnValue: 0)
          as int);

  @override
  String get levelTitle =>
      (super.noSuchMethod(
            Invocation.getter(#levelTitle),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#levelTitle),
            ),
          )
          as String);

  @override
  int get currentXP =>
      (super.noSuchMethod(Invocation.getter(#currentXP), returnValue: 0)
          as int);

  @override
  int get xpForNextLevel =>
      (super.noSuchMethod(Invocation.getter(#xpForNextLevel), returnValue: 0)
          as int);

  @override
  int get totalXP =>
      (super.noSuchMethod(Invocation.getter(#totalXP), returnValue: 0) as int);

  @override
  double get xpProgress =>
      (super.noSuchMethod(Invocation.getter(#xpProgress), returnValue: 0.0)
          as double);

  @override
  int get xpRemaining =>
      (super.noSuchMethod(Invocation.getter(#xpRemaining), returnValue: 0)
          as int);

  @override
  int get progressPercentage =>
      (super.noSuchMethod(
            Invocation.getter(#progressPercentage),
            returnValue: 0,
          )
          as int);

  @override
  bool get isMaxLevel =>
      (super.noSuchMethod(Invocation.getter(#isMaxLevel), returnValue: false)
          as bool);

  @override
  _i2.UserLevelModel copyWith({
    int? currentLevel,
    String? levelTitle,
    int? currentXP,
    int? xpForNextLevel,
    int? totalXP,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #currentLevel: currentLevel,
              #levelTitle: levelTitle,
              #currentXP: currentXP,
              #xpForNextLevel: xpForNextLevel,
              #totalXP: totalXP,
            }),
            returnValue: _FakeUserLevelModel_0(
              this,
              Invocation.method(#copyWith, [], {
                #currentLevel: currentLevel,
                #levelTitle: levelTitle,
                #currentXP: currentXP,
                #xpForNextLevel: xpForNextLevel,
                #totalXP: totalXP,
              }),
            ),
          )
          as _i2.UserLevelModel);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [BadgeModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeModel extends _i1.Mock implements _i5.BadgeModel {
  MockBadgeModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  _i3.IconData get icon =>
      (super.noSuchMethod(
            Invocation.getter(#icon),
            returnValue: _FakeIconData_1(this, Invocation.getter(#icon)),
          )
          as _i3.IconData);

  @override
  bool get isEarned =>
      (super.noSuchMethod(Invocation.getter(#isEarned), returnValue: false)
          as bool);

  @override
  double get progress =>
      (super.noSuchMethod(Invocation.getter(#progress), returnValue: 0.0)
          as double);

  @override
  _i5.BadgeCategory get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i5.BadgeCategory.prayer,
          )
          as _i5.BadgeCategory);

  @override
  _i4.Color get color =>
      (super.noSuchMethod(
            Invocation.getter(#color),
            returnValue: _FakeColor_2(this, Invocation.getter(#color)),
          )
          as _i4.Color);

  @override
  String get categoryText =>
      (super.noSuchMethod(
            Invocation.getter(#categoryText),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#categoryText),
            ),
          )
          as String);

  @override
  _i5.BadgeModel copyWith({
    String? userId,
    String? id,
    String? title,
    String? description,
    String? iconUrl,
    _i3.IconData? icon,
    bool? isEarned,
    double? progress,
    DateTime? earnedDate,
    _i5.BadgeCategory? category,
    _i4.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #userId: userId,
              #id: id,
              #title: title,
              #description: description,
              #iconUrl: iconUrl,
              #icon: icon,
              #isEarned: isEarned,
              #progress: progress,
              #earnedDate: earnedDate,
              #category: category,
              #color: color,
            }),
            returnValue: _FakeBadgeModel_3(
              this,
              Invocation.method(#copyWith, [], {
                #userId: userId,
                #id: id,
                #title: title,
                #description: description,
                #iconUrl: iconUrl,
                #icon: icon,
                #isEarned: isEarned,
                #progress: progress,
                #earnedDate: earnedDate,
                #category: category,
                #color: color,
              }),
            ),
          )
          as _i5.BadgeModel);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<_i4.Color> getGradientColors() =>
      (super.noSuchMethod(
            Invocation.method(#getGradientColors, []),
            returnValue: <_i4.Color>[],
          )
          as List<_i4.Color>);

  @override
  _i4.Color getBadgeColor() =>
      (super.noSuchMethod(
            Invocation.method(#getBadgeColor, []),
            returnValue: _FakeColor_2(
              this,
              Invocation.method(#getBadgeColor, []),
            ),
          )
          as _i4.Color);
}

/// A class which mocks [LeaderboardUserModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaderboardUserModel extends _i1.Mock
    implements _i6.LeaderboardUserModel {
  MockLeaderboardUserModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get rank =>
      (super.noSuchMethod(Invocation.getter(#rank), returnValue: 0) as int);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  int get xp =>
      (super.noSuchMethod(Invocation.getter(#xp), returnValue: 0) as int);

  @override
  bool get isCurrentUser =>
      (super.noSuchMethod(Invocation.getter(#isCurrentUser), returnValue: false)
          as bool);

  @override
  String get rankDisplay =>
      (super.noSuchMethod(
            Invocation.getter(#rankDisplay),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#rankDisplay),
            ),
          )
          as String);

  @override
  bool get hasMedal =>
      (super.noSuchMethod(Invocation.getter(#hasMedal), returnValue: false)
          as bool);

  @override
  _i6.LeaderboardUserModel copyWith({
    int? rank,
    String? name,
    String? avatarUrl,
    int? xp,
    bool? isCurrentUser,
    String? badge,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #rank: rank,
              #name: name,
              #avatarUrl: avatarUrl,
              #xp: xp,
              #isCurrentUser: isCurrentUser,
              #badge: badge,
            }),
            returnValue: _FakeLeaderboardUserModel_4(
              this,
              Invocation.method(#copyWith, [], {
                #rank: rank,
                #name: name,
                #avatarUrl: avatarUrl,
                #xp: xp,
                #isCurrentUser: isCurrentUser,
                #badge: badge,
              }),
            ),
          )
          as _i6.LeaderboardUserModel);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
