// Mocks generated by Mockito 5.4.6 from annotations
// in daily_life_tracker/test/providers/project_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i10;

import 'package:daily_life_tracker/models/badge_model.dart' as _i8;
import 'package:daily_life_tracker/models/leaderboard_user_model.dart' as _i9;
import 'package:daily_life_tracker/models/project_model.dart' as _i4;
import 'package:daily_life_tracker/models/subtask_model.dart' as _i6;
import 'package:daily_life_tracker/providers/achievements_provider.dart' as _i7;
import 'package:daily_life_tracker/services/project_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProjectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectService extends _i1.Mock implements _i2.ProjectService {
  MockProjectService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Project>> fetchProjects() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProjects, []),
            returnValue: _i3.Future<List<_i4.Project>>.value(<_i4.Project>[]),
          )
          as _i3.Future<List<_i4.Project>>);

  @override
  _i3.Future<String> createProject(_i4.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#createProject, [project]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createProject, [project]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateProject(_i4.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#updateProject, [project]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [projectId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleProjectStatus(
    String? projectId,
    _i4.ProjectStatus? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleProjectStatus, [projectId, newStatus]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProjectProgress(String? projectId, double? progress) =>
      (super.noSuchMethod(
            Invocation.method(#updateProjectProgress, [projectId, progress]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logProjectTime(String? projectId, int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#logProjectTime, [projectId, minutes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchProjectTimeLogs(
    String? projectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProjectTimeLogs, [projectId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> getTotalTimeSpent(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalTimeSpent, [projectId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i6.Subtask>> fetchSubTasks(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubTasks, [projectId]),
            returnValue: _i3.Future<List<_i6.Subtask>>.value(<_i6.Subtask>[]),
          )
          as _i3.Future<List<_i6.Subtask>>);

  @override
  _i3.Future<String> createSubTask(_i6.Subtask? subtask) =>
      (super.noSuchMethod(
            Invocation.method(#createSubTask, [subtask]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createSubTask, [subtask]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateSubTask(_i6.Subtask? subtask) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubTask, [subtask]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSubTask(String? subtaskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubTask, [subtaskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleSubTaskCompletion(
    String? subtaskId,
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSubTaskCompletion, [
              subtaskId,
              isCompleted,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AchievementsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementsProvider extends _i1.Mock
    implements _i7.AchievementsProvider {
  MockAchievementsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.BadgeModel> get earnedBadges =>
      (super.noSuchMethod(
            Invocation.getter(#earnedBadges),
            returnValue: <_i8.BadgeModel>[],
          )
          as List<_i8.BadgeModel>);

  @override
  List<_i8.BadgeModel> get lockedBadges =>
      (super.noSuchMethod(
            Invocation.getter(#lockedBadges),
            returnValue: <_i8.BadgeModel>[],
          )
          as List<_i8.BadgeModel>);

  @override
  List<_i8.BadgeModel> get allBadges =>
      (super.noSuchMethod(
            Invocation.getter(#allBadges),
            returnValue: <_i8.BadgeModel>[],
          )
          as List<_i8.BadgeModel>);

  @override
  List<_i8.BadgeModel> get badges =>
      (super.noSuchMethod(
            Invocation.getter(#badges),
            returnValue: <_i8.BadgeModel>[],
          )
          as List<_i8.BadgeModel>);

  @override
  List<_i9.LeaderboardUserModel> get leaderboard =>
      (super.noSuchMethod(
            Invocation.getter(#leaderboard),
            returnValue: <_i9.LeaderboardUserModel>[],
          )
          as List<_i9.LeaderboardUserModel>);

  @override
  int get earnedBadgeCount =>
      (super.noSuchMethod(Invocation.getter(#earnedBadgeCount), returnValue: 0)
          as int);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get currentLevelPoints =>
      (super.noSuchMethod(
            Invocation.getter(#currentLevelPoints),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> loadAchievementsData() =>
      (super.noSuchMethod(
            Invocation.method(#loadAchievementsData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> earnBadge(String? badgeId) =>
      (super.noSuchMethod(
            Invocation.method(#earnBadge, [badgeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addXP(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#addXP, [amount]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshLeaderboard() =>
      (super.noSuchMethod(
            Invocation.method(#refreshLeaderboard, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
