// Mocks generated by Mockito 5.4.6 from annotations
// in daily_life_tracker/test/providers/stats_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i15;

import 'package:daily_life_tracker/models/badge_model.dart' as _i18;
import 'package:daily_life_tracker/models/leaderboard_user_model.dart' as _i19;
import 'package:daily_life_tracker/models/project_model.dart' as _i9;
import 'package:daily_life_tracker/models/report_model.dart' as _i7;
import 'package:daily_life_tracker/models/stats_model.dart' as _i5;
import 'package:daily_life_tracker/models/subtask_model.dart' as _i11;
import 'package:daily_life_tracker/models/task_model.dart' as _i13;
import 'package:daily_life_tracker/models/user_level_model.dart' as _i2;
import 'package:daily_life_tracker/providers/achievements_provider.dart'
    as _i14;
import 'package:daily_life_tracker/providers/project_provider.dart' as _i16;
import 'package:daily_life_tracker/providers/task_provider.dart' as _i12;
import 'package:daily_life_tracker/providers/water_provider.dart' as _i17;
import 'package:daily_life_tracker/services/project_service.dart' as _i8;
import 'package:daily_life_tracker/services/reports_service.dart' as _i6;
import 'package:daily_life_tracker/services/stats_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserLevelModel_0 extends _i1.SmartFake
    implements _i2.UserLevelModel {
  _FakeUserLevelModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StatsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsService extends _i1.Mock implements _i3.StatsService {
  MockStatsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>?> fetchDailyStats(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDailyStats,
          [date],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<double> calculateWeeklyProductivity() => (super.noSuchMethod(
        Invocation.method(
          #calculateWeeklyProductivity,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<List<_i5.WeeklyStats>> getWeeklyChartData() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklyChartData,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.WeeklyStats>>.value(<_i5.WeeklyStats>[]),
      ) as _i4.Future<List<_i5.WeeklyStats>>);

  @override
  _i4.Future<List<_i5.TimeDistribution>> calculateTimeDistribution() =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateTimeDistribution,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TimeDistribution>>.value(
            <_i5.TimeDistribution>[]),
      ) as _i4.Future<List<_i5.TimeDistribution>>);

  @override
  _i4.Future<List<_i5.Achievement>> getWeeklyAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyAchievements,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.Achievement>>.value(<_i5.Achievement>[]),
      ) as _i4.Future<List<_i5.Achievement>>);

  @override
  _i4.Future<void> saveDailyStats({
    required int? completedTasksCount,
    required int? totalTasksCount,
    required int? waterIntakeMl,
    required double? projectHours,
    required double? completionPercentage,
    required int? xpEarned,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDailyStats,
          [],
          {
            #completedTasksCount: completedTasksCount,
            #totalTasksCount: totalTasksCount,
            #waterIntakeMl: waterIntakeMl,
            #projectHours: projectHours,
            #completionPercentage: completionPercentage,
            #xpEarned: xpEarned,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ReportsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportsService extends _i1.Mock implements _i6.ReportsService {
  MockReportsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.DailyReportModel>> fetchDailyReport(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDailyReport,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<List<_i7.DailyReportModel>>.value(
            <_i7.DailyReportModel>[]),
      ) as _i4.Future<List<_i7.DailyReportModel>>);

  @override
  _i4.Future<List<_i7.DailyReportModel>> fetchWeeklyReport() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWeeklyReport,
          [],
        ),
        returnValue: _i4.Future<List<_i7.DailyReportModel>>.value(
            <_i7.DailyReportModel>[]),
      ) as _i4.Future<List<_i7.DailyReportModel>>);

  @override
  _i4.Future<List<_i7.ProjectReportModel>> fetchProjectsReport() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProjectsReport,
          [],
        ),
        returnValue: _i4.Future<List<_i7.ProjectReportModel>>.value(
            <_i7.ProjectReportModel>[]),
      ) as _i4.Future<List<_i7.ProjectReportModel>>);

  @override
  _i4.Future<Map<String, double>> calculateWeeklyProductivityFromReport() =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateWeeklyProductivityFromReport,
          [],
        ),
        returnValue: _i4.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i4.Future<Map<String, double>>);
}

/// A class which mocks [ProjectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectService extends _i1.Mock implements _i8.ProjectService {
  MockProjectService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i9.Project>> fetchProjects() => (super.noSuchMethod(
        Invocation.method(
          #fetchProjects,
          [],
        ),
        returnValue: _i4.Future<List<_i9.Project>>.value(<_i9.Project>[]),
      ) as _i4.Future<List<_i9.Project>>);

  @override
  _i4.Future<String> createProject(_i9.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [project],
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #createProject,
            [project],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateProject(_i9.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [project],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [projectId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleProjectStatus(
    String? projectId,
    _i9.ProjectStatus? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleProjectStatus,
          [
            projectId,
            newStatus,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProjectProgress(
    String? projectId,
    double? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProjectProgress,
          [
            projectId,
            progress,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logProjectTime(
    String? projectId,
    int? minutes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logProjectTime,
          [
            projectId,
            minutes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchProjectTimeLogs(
          String? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProjectTimeLogs,
          [projectId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> getTotalTimeSpent(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalTimeSpent,
          [projectId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i11.Subtask>> fetchSubTasks(String? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSubTasks,
          [projectId],
        ),
        returnValue: _i4.Future<List<_i11.Subtask>>.value(<_i11.Subtask>[]),
      ) as _i4.Future<List<_i11.Subtask>>);

  @override
  _i4.Future<String> createSubTask(_i11.Subtask? subtask) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubTask,
          [subtask],
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #createSubTask,
            [subtask],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateSubTask(_i11.Subtask? subtask) => (super.noSuchMethod(
        Invocation.method(
          #updateSubTask,
          [subtask],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSubTask(String? subtaskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSubTask,
          [subtaskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleSubTaskCompletion(
    String? subtaskId,
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleSubTaskCompletion,
          [
            subtaskId,
            isCompleted,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TaskProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskProvider extends _i1.Mock implements _i12.TaskProvider {
  MockTaskProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.Task> get tasks => (super.noSuchMethod(
        Invocation.getter(#tasks),
        returnValue: <_i13.Task>[],
      ) as List<_i13.Task>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setAchievementsProvider(
          _i14.AchievementsProvider? achievementsProvider) =>
      super.noSuchMethod(
        Invocation.method(
          #setAchievementsProvider,
          [achievementsProvider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #toggleTask,
          [taskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i13.Task> getTasksByCategory(String? category) => (super.noSuchMethod(
        Invocation.method(
          #getTasksByCategory,
          [category],
        ),
        returnValue: <_i13.Task>[],
      ) as List<_i13.Task>);

  @override
  double getCompletionPercentage() => (super.noSuchMethod(
        Invocation.method(
          #getCompletionPercentage,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> addTask(_i13.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshTasks() => (super.noSuchMethod(
        Invocation.method(
          #refreshTasks,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProjectProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectProvider extends _i1.Mock implements _i16.ProjectProvider {
  MockProjectProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.Project> get projects => (super.noSuchMethod(
        Invocation.getter(#projects),
        returnValue: <_i9.Project>[],
      ) as List<_i9.Project>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i9.Project> get activeProjects => (super.noSuchMethod(
        Invocation.getter(#activeProjects),
        returnValue: <_i9.Project>[],
      ) as List<_i9.Project>);

  @override
  List<_i9.Project> get pausedProjects => (super.noSuchMethod(
        Invocation.getter(#pausedProjects),
        returnValue: <_i9.Project>[],
      ) as List<_i9.Project>);

  @override
  List<_i9.Project> get completedProjects => (super.noSuchMethod(
        Invocation.getter(#completedProjects),
        returnValue: <_i9.Project>[],
      ) as List<_i9.Project>);

  @override
  List<_i9.Project> get allProjects => (super.noSuchMethod(
        Invocation.getter(#allProjects),
        returnValue: <_i9.Project>[],
      ) as List<_i9.Project>);

  @override
  int get activeProjectsCount => (super.noSuchMethod(
        Invocation.getter(#activeProjectsCount),
        returnValue: 0,
      ) as int);

  @override
  int get pausedProjectsCount => (super.noSuchMethod(
        Invocation.getter(#pausedProjectsCount),
        returnValue: 0,
      ) as int);

  @override
  int get completedProjectsCount => (super.noSuchMethod(
        Invocation.getter(#completedProjectsCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setAchievementsProvider(
          _i14.AchievementsProvider? achievementsProvider) =>
      super.noSuchMethod(
        Invocation.method(
          #setAchievementsProvider,
          [achievementsProvider],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getMonthlyProgress() => (super.noSuchMethod(
        Invocation.method(
          #getMonthlyProgress,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> toggleProjectStatus(String? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleProjectStatus,
          [projectId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProjectProgress(
    String? projectId,
    double? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProjectProgress,
          [
            projectId,
            progress,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addProject(_i9.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #addProject,
          [project],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshProjects() => (super.noSuchMethod(
        Invocation.method(
          #refreshProjects,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProject(_i9.Project? updatedProject) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [updatedProject],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [projectId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i9.Project? getProjectById(String? projectId) =>
      (super.noSuchMethod(Invocation.method(
        #getProjectById,
        [projectId],
      )) as _i9.Project?);

  @override
  String generateProjectId() => (super.noSuchMethod(
        Invocation.method(
          #generateProjectId,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #generateProjectId,
            [],
          ),
        ),
      ) as String);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> loadProjects() => (super.noSuchMethod(
        Invocation.method(
          #loadProjects,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WaterProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWaterProvider extends _i1.Mock implements _i17.WaterProvider {
  MockWaterProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentCups => (super.noSuchMethod(
        Invocation.getter(#currentCups),
        returnValue: 0,
      ) as int);

  @override
  int get targetCups => (super.noSuchMethod(
        Invocation.getter(#targetCups),
        returnValue: 0,
      ) as int);

  @override
  int get currentIntakeMl => (super.noSuchMethod(
        Invocation.getter(#currentIntakeMl),
        returnValue: 0,
      ) as int);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addCup() => (super.noSuchMethod(
        Invocation.method(
          #addCup,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getProgress() => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> refreshWaterData() => (super.noSuchMethod(
        Invocation.method(
          #refreshWaterData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AchievementsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementsProvider extends _i1.Mock
    implements _i14.AchievementsProvider {
  MockAchievementsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i18.BadgeModel> get earnedBadges => (super.noSuchMethod(
        Invocation.getter(#earnedBadges),
        returnValue: <_i18.BadgeModel>[],
      ) as List<_i18.BadgeModel>);

  @override
  List<_i18.BadgeModel> get lockedBadges => (super.noSuchMethod(
        Invocation.getter(#lockedBadges),
        returnValue: <_i18.BadgeModel>[],
      ) as List<_i18.BadgeModel>);

  @override
  List<_i18.BadgeModel> get allBadges => (super.noSuchMethod(
        Invocation.getter(#allBadges),
        returnValue: <_i18.BadgeModel>[],
      ) as List<_i18.BadgeModel>);

  @override
  List<_i18.BadgeModel> get badges => (super.noSuchMethod(
        Invocation.getter(#badges),
        returnValue: <_i18.BadgeModel>[],
      ) as List<_i18.BadgeModel>);

  @override
  List<_i19.LeaderboardUserModel> get leaderboard => (super.noSuchMethod(
        Invocation.getter(#leaderboard),
        returnValue: <_i19.LeaderboardUserModel>[],
      ) as List<_i19.LeaderboardUserModel>);

  @override
  int get earnedBadgeCount => (super.noSuchMethod(
        Invocation.getter(#earnedBadgeCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get currentLevelPoints => (super.noSuchMethod(
        Invocation.getter(#currentLevelPoints),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadAchievementsData() => (super.noSuchMethod(
        Invocation.method(
          #loadAchievementsData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> earnBadge(String? badgeId) => (super.noSuchMethod(
        Invocation.method(
          #earnBadge,
          [badgeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addXP(int? amount) => (super.noSuchMethod(
        Invocation.method(
          #addXP,
          [amount],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshLeaderboard() => (super.noSuchMethod(
        Invocation.method(
          #refreshLeaderboard,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserLevelModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLevelModel extends _i1.Mock implements _i2.UserLevelModel {
  MockUserLevelModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentLevel => (super.noSuchMethod(
        Invocation.getter(#currentLevel),
        returnValue: 0,
      ) as int);

  @override
  String get levelTitle => (super.noSuchMethod(
        Invocation.getter(#levelTitle),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#levelTitle),
        ),
      ) as String);

  @override
  int get currentXP => (super.noSuchMethod(
        Invocation.getter(#currentXP),
        returnValue: 0,
      ) as int);

  @override
  int get xpForNextLevel => (super.noSuchMethod(
        Invocation.getter(#xpForNextLevel),
        returnValue: 0,
      ) as int);

  @override
  int get totalXP => (super.noSuchMethod(
        Invocation.getter(#totalXP),
        returnValue: 0,
      ) as int);

  @override
  double get xpProgress => (super.noSuchMethod(
        Invocation.getter(#xpProgress),
        returnValue: 0.0,
      ) as double);

  @override
  int get xpRemaining => (super.noSuchMethod(
        Invocation.getter(#xpRemaining),
        returnValue: 0,
      ) as int);

  @override
  int get progressPercentage => (super.noSuchMethod(
        Invocation.getter(#progressPercentage),
        returnValue: 0,
      ) as int);

  @override
  bool get isMaxLevel => (super.noSuchMethod(
        Invocation.getter(#isMaxLevel),
        returnValue: false,
      ) as bool);

  @override
  _i2.UserLevelModel copyWith({
    int? currentLevel,
    String? levelTitle,
    int? currentXP,
    int? xpForNextLevel,
    int? totalXP,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #currentLevel: currentLevel,
            #levelTitle: levelTitle,
            #currentXP: currentXP,
            #xpForNextLevel: xpForNextLevel,
            #totalXP: totalXP,
          },
        ),
        returnValue: _FakeUserLevelModel_0(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #currentLevel: currentLevel,
              #levelTitle: levelTitle,
              #currentXP: currentXP,
              #xpForNextLevel: xpForNextLevel,
              #totalXP: totalXP,
            },
          ),
        ),
      ) as _i2.UserLevelModel);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
