// Mocks generated by Mockito 5.4.6 from annotations
// in daily_life_tracker/test/providers/task_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i9;

import 'package:daily_life_tracker/models/badge_model.dart' as _i7;
import 'package:daily_life_tracker/models/leaderboard_user_model.dart' as _i8;
import 'package:daily_life_tracker/models/task_model.dart' as _i4;
import 'package:daily_life_tracker/providers/achievements_provider.dart' as _i6;
import 'package:daily_life_tracker/services/task_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i2.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Task>> fetchTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTasks, []),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<String> createTask(_i4.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createTask, [task]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateTask(_i4.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleTaskCompletion(String? taskId, bool? isCompleted) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTaskCompletion, [taskId, isCompleted]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AchievementsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementsProvider extends _i1.Mock
    implements _i6.AchievementsProvider {
  MockAchievementsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.BadgeModel> get earnedBadges =>
      (super.noSuchMethod(
            Invocation.getter(#earnedBadges),
            returnValue: <_i7.BadgeModel>[],
          )
          as List<_i7.BadgeModel>);

  @override
  List<_i7.BadgeModel> get lockedBadges =>
      (super.noSuchMethod(
            Invocation.getter(#lockedBadges),
            returnValue: <_i7.BadgeModel>[],
          )
          as List<_i7.BadgeModel>);

  @override
  List<_i7.BadgeModel> get allBadges =>
      (super.noSuchMethod(
            Invocation.getter(#allBadges),
            returnValue: <_i7.BadgeModel>[],
          )
          as List<_i7.BadgeModel>);

  @override
  List<_i7.BadgeModel> get badges =>
      (super.noSuchMethod(
            Invocation.getter(#badges),
            returnValue: <_i7.BadgeModel>[],
          )
          as List<_i7.BadgeModel>);

  @override
  List<_i8.LeaderboardUserModel> get leaderboard =>
      (super.noSuchMethod(
            Invocation.getter(#leaderboard),
            returnValue: <_i8.LeaderboardUserModel>[],
          )
          as List<_i8.LeaderboardUserModel>);

  @override
  int get earnedBadgeCount =>
      (super.noSuchMethod(Invocation.getter(#earnedBadgeCount), returnValue: 0)
          as int);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get currentLevelPoints =>
      (super.noSuchMethod(
            Invocation.getter(#currentLevelPoints),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> loadAchievementsData() =>
      (super.noSuchMethod(
            Invocation.method(#loadAchievementsData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> earnBadge(String? badgeId) =>
      (super.noSuchMethod(
            Invocation.method(#earnBadge, [badgeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addXP(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#addXP, [amount]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshLeaderboard() =>
      (super.noSuchMethod(
            Invocation.method(#refreshLeaderboard, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
