// Mocks generated by Mockito 5.4.6 from annotations
// in daily_life_tracker/test/providers/water_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:daily_life_tracker/models/water_log_model.dart' as _i4;
import 'package:daily_life_tracker/services/water_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WaterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWaterService extends _i1.Mock implements _i2.WaterService {
  MockWaterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logWaterIntake(int? amountMl) => (super.noSuchMethod(
        Invocation.method(
          #logWaterIntake,
          [amountMl],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.WaterLog>> fetchTodayWaterLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchTodayWaterLogs,
          [],
        ),
        returnValue: _i3.Future<List<_i4.WaterLog>>.value(<_i4.WaterLog>[]),
      ) as _i3.Future<List<_i4.WaterLog>>);

  @override
  _i3.Future<int> getTodayWaterIntake() => (super.noSuchMethod(
        Invocation.method(
          #getTodayWaterIntake,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getWaterGoal() => (super.noSuchMethod(
        Invocation.method(
          #getWaterGoal,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
